### ISSUE TITLE
Timeout errors in CouchDB

### ISSUE THREAD

**Issue by redgeoff** [redgeoff/spiegel#100]
There appears to be a bug in CouchDB 2.1 (and possibly other versions) that results in timeout errors like the following when Spiegel first starts up on a fresh database. This was rather consistent during stress testing. Previously, both the [quelle](https://github.com/redgeoff/quelle/blob/6be08a9842e82c6d70c134523f1cf3af042e8caf/scripts/persistent-stream.js#L108) and [slouch](https://github.com/redgeoff/slouch/blob/174c95cf90c5df2534edbf35c2a2930b3cfe5637/scripts/enhanced-request.js#L203) layers had logic in place to retry when there is a `timeout` error, but immediately retry with continuous listening leads to a deadlock where CouchDB request appears to just hang. Instead, the most reliable option is to throw a permanent error at the quelle and slouch layers and have the spiegel process completely restart, e.g. via Docker.

```
{
	"name": "spiegel",
	"hostname": "ubuntu-xenial",
	"pid": 29897,
	"level": 60,
	"err": {
		"message": "reason={timeout,{gen_server,call,\n                     [couch_proc_manager,\n                      {get_proc,{doc,<<\"_design/dirty_and_unlocked_replicator\">>,\n                                     {1,\n                                      [<<131,177,171,194,217,1,115,189,75,19,\n                                         89,111,86,169,253,113>>]},\n                                     {[{<<\"views\">>,\n                                        {[{<<\"dirty_and_unlocked_replicator\">>,\n                                           {[{<<\"map\">>,\n                                              <<\"function(doc) { if (doc.type === \\\"replicator\\\" && doc.dirty !== false && !doc.locked_at) { emit(doc._id, null); } }\">>}]}}]}}]},\n                                     [],false,[]},\n                                {<<\"_design/dirty_and_unlocked_replicator\">>,\n                                 <<\"1-83b1abc2d90173bd4b13596f56a9fd71\">>}},\n                      5000]}}, error=error, opts={\"url\":\"http://admin:**********@192.168.50.11:5984/spiegel/_changes\",\"method\":\"GET\",\"qs\":{\"limit\":1,\"descending\":true,\"filter\":\"_view\",\"view\":\"dirty_and_unlocked_replicator/dirty_and_unlocked_replicator\"}}",
		"name": "Error",
		"stack": "Error: reason={timeout,{gen_server,call,\n                     [couch_proc_manager,\n                      {get_proc,{doc,<<\"_design/dirty_and_unlocked_replicator\">>,\n                                     {1,\n                                      [<<131,177,171,194,217,1,115,189,75,19,\n                                         89,111,86,169,253,113>>]},\n                                     {[{<<\"views\">>,\n                                        {[{<<\"dirty_and_unlocked_replicator\">>,\n                                           {[{<<\"map\">>,\n                                              <<\"function(doc) { if (doc.type === \\\"replicator\\\" && doc.dirty !== false && !doc.locked_at) { emit(doc._id, null); } }\">>}]}}]}}]},\n                                     [],false,[]},\n                                {<<\"_design/dirty_and_unlocked_replicator\">>,\n                                 <<\"1-83b1abc2d90173bd4b13596f56a9fd71\">>}},\n                      5000]}}, error=error, opts={\"url\":\"http://admin:**********@192.168.50.11:5984/spiegel/_changes\",\"method\":\"GET\",\"qs\":{\"limit\":1,\"descending\":true,\"filter\":\"_view\",\"view\":\"dirty_and_unlocked_replicator/dirty_and_unlocked_replicator\"}}\n    at CouchPersistentStreamIterator._onceData (/vagrant/app/db-per-user-benchmark/node_modules/couch-slouch/scripts/couch-persistent-stream-iterator.js:29:22)\n    at Request.<anonymous> (/vagrant/app/db-per-user-benchmark/node_modules/quelle/scripts/persistent-stream-iterator.js:92:16)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:121:20)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/vagrant/app/db-per-user-benchmark/node_modules/request/request.js:1082:12)\n    at emitOne (events.js:116:13)\n    at IncomingMessage.emit (events.js:211:7)\n    at IncomingMessage.Readable.read (_stream_readable.js:475:10)\n    at flow (_stream_readable.js:846:34)\n    at resume_ (_stream_readable.js:828:3)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
	},
	"msg": "reason={timeout,{gen_server,call,\n                     [couch_proc_manager,\n                      {get_proc,{doc,<<\"_design/dirty_and_unlocked_replicator\">>,\n                                     {1,\n                                      [<<131,177,171,194,217,1,115,189,75,19,\n                                         89,111,86,169,253,113>>]},\n                                     {[{<<\"views\">>,\n                                        {[{<<\"dirty_and_unlocked_replicator\">>,\n                                           {[{<<\"map\">>,\n                                              <<\"function(doc) { if (doc.type === \\\"replicator\\\" && doc.dirty !== false && !doc.locked_at) { emit(doc._id, null); } }\">>}]}}]}}]},\n                                     [],false,[]},\n                                {<<\"_design/dirty_and_unlocked_replicator\">>,\n                                 <<\"1-83b1abc2d90173bd4b13596f56a9fd71\">>}},\n                      5000]}}, error=error, opts={\"url\":\"http://admin:**********@192.168.50.11:5984/spiegel/_changes\",\"method\":\"GET\",\"qs\":{\"limit\":1,\"descending\":true,\"filter\":\"_view\",\"view\":\"dirty_and_unlocked_replicator/dirty_and_unlocked_replicator\"}}",
	"time": "2018-01-21T14:45:26.708Z",
	"src": {
		"file": "/vagrant/app/db-per-user-benchmark/node_modules/spiegel/src/log.js",
		"line": 10,
		"func": "log.fatal"
	},
	"v": 0
}
```

TODO: Hopefully this bug will be fixed in CouchDB and this issue can be closed. If not, an isolated test environment should be created to expose this bug.

**Comment by redgeoff** [comment]
I think these errors may have been fixed by CouchDB2.2.
